
# Mapping table names to models and their fields

field_name = {
    "program": [
        "name",
        "description",
    ],
    "proce_csv_manual": [
        "isactive_flag",
        "code_crl",
        "price",
    ],
    "contact": [
        "account_name",
        "account_phone",
        "account_type",
        "account_description",
        "account_id",
        "account_source",
        "alpha_name",
        "billing_city",
        "billing_country",
        "billing_group",
        "billing_state_province",
        "billing_street",
        "billing_zip_postal_Code",
        "canopy_currency",
        "canopy_customer_code",
        "canopy_customer_key",
        "canopy_pricing_grp",
        "canopy_vendor_code",
        "industry",
        "ship_to_contact_name",
        "ship_to_display",
        "shipping_city",
        "shipping_country",
        "shipping_state_province",
        "shipping_street",
        "shipping_zip_postal_code",
        "vendor_ship_from",
        "website",
    ],
    "email": [
        "business_phone",
        "email",
        "first_name",
        "last_name",
        "title",
        "account_id",
        "business_fax",
        "contact_cd",
        "contact_display",
        "contact_id",
        "full_name",
        "sms_opt_out"
    ],
    "product": [
        "status",
        "code_crl",
        "description",
        "species",
        "product_type",
        "age_days",
        "freeze_down",
        "case_size",
        "bag_size",
        "ecoli_test",
        "pieces_box",
        "bags_box",
        "gtin12",
        "gtin14",
        "pack_type",
        "net_wgt",
        "growss_wt",
        "dim_l",
        "dim_w",
        "dim_h",
        "dim_um",
        "pallet_tier",
        "pallet_layers",
    ],
    "CutOutMap": [
        "mail_id",
        "date",
        "lot_number",
        "hd_amount",
        "type_grade",
        "lw_in_kg",
        "lw_avg_kg",
        "lw_avg_lbs",
        "hhw_in_kg",
        "hhw_avg_kg",
        "hhw_avg_lbs",
        "yield_dress",
        "cw_in_kg",
        "cw_shrink",
        "cw_avg_kg",
        "cw_avg_lbs",
        "live_dollar_per_kg",
        "yield_cut",
        "hhw_dollar_per_kg",
        "hhw_avg_kg_yield",
        "hhw_avg_lbs_yield",
        "yield_meat",
        "bulls_amount",
        "heifers_amount",
        "cows_amount",
        "mature",
        "hhw_hd_dollar_kg",
        "cost_hhw",
        "cost_plant_hd",
        "cost_plant",
        "cost_fob",
        "cost_sga_lb",
        "cost_sga",
        "cost_kill",
        "sell_primal",
        "sell_offal",
        "sell_profit",
        "sell_primal_hd",
        "sell_offal_hd",
        "margin",
        "sell_hd",
        "cost_hd",
        "profit_hd",
        "eu_fx",
        "kgs_total",
        "code_crl",
        "sell_kg",
        "kgs_hd",
        "value_total",
        "wt_percent_cuts",
        "value_percent",
        "cogs_kg",
        "cogs",
    ],
    "slaughter_rep": [
        "animal_pk",
        "animal_iden",
        "slaughter_date",
        "owner",
        "shipper",
        "live_weight",
        "hot_weight",
        "cold_weight",
        "age",
        "receiving_order_id",
        "condemn_flag",
        "lot_number",
        "species",
        "sex",
        "manifest_iden",
        "grading",
        "csf_date"
    ]
}

header_names = {
    "program": ["name",
                "description"],
    "price_csv_manual": [
        "isactive",
        "code_crl",
        "price",
    ],
    "price": [
        "isactive",
        "code_crl",
        "price",
        "cur_unit",
        "eft_date",
    ],
    "contact": [
        "Account Name",
        "Account Phone",
        "Account Type",
        "Account Description",
        "Account ID",
        "Account Source",
        "Alpha Name",
        "Billing City",
        "Billing Country",
        "Billing Group",
        "Billing State/Province",
        "Billing Street",
        "Billing Zip/Postal Code",
        "Canopy Currency",
        "Canopy Customer Code",
        "Canopy Customer Key",
        "Canopy Pricing Grp",
        "Canopy Vendor Code",
        "Industry",
        "Ship To Contact Name",
        "Ship-To-Display",
        "Shipping City",
        "Shipping Country",
        "Shipping State/Province",
        "Shipping Street",
        "Shipping Zip/Postal Code",
        "Vendor Ship From",
        "Website"
    ],
    "email": [
        "Business Phone",
        "Email",
        "First Name",
        "Last Name",
        "Title",
        "Account ID",
        "Business Fax",
        "Contact Cd",
        "Contact Display",
        "Contact ID",
        "Full Name",
        "SMS Opt Out"
    ],
    "CutOutMap": [
        "mail_id",
        "date",
        "lot_number",
        "hd_amount",
        "type",
        "lw_in_kg",
        "lw_avg_kg",
        "lw_avg_lbs",
        "hhw_in_kg",
        "hhw_avg_kg",
        "hhw_avg_lbs",
        "yield_dress",
        "cw_in_kg",
        "cw_shrink",
        "cw_avg_kg",
        "cw_avg_lbs",
        "live_dollar_per_kg",
        "yield_cut",
        "hhw_dollar_per_kg",
        "hhw_avg_kg_yield",
        "hhw_avg_lbs_yield",
        "yield_meat",
        "bulls_amount",
        "heifers_amount",
        "cows_amount",
        "mature",
        "hhw_hd_dollar_kg",
        "cost_hhw",
        "cost_plant_hd",
        "cost_plant",
        "cost_fob",
        "cost_sga_lb",
        "cost_sga",
        "cost_kill",
        "sell_primal",
        "sell_offal",
        "sell_profit",
        "sell_primal_hd",
        "sell_offal_hd",
        "margin",
        "sell_hd",
        "cost_hd",
        "profit_hd",
        "eu_fx",
        "kgs_total",
        "code_crl",
        "sell_kg",
        "kgs_hd",
        "value_total",
        "wt_percent_cuts",
        "value_percent",
        "cogs_kg",
        "cogs",
    ],
    "product_manual": [
        "CODE_UID",
        "CODE_CRL",
        "STATUS ",
        "CODE_PFF",
        "PROGRAM",
        "CODE_PFFshort",
        "CODE_CPM",
        "CODE_MR",
        "CODE_CFS",
        "CODE_BMP",
        "CODE_RMNM",
        "CODE_SKFP",
        "CODE_MCF",
        "CODE_NF",
        "DISCRIPTION",
        "CUT_TYPE",
        "SPECIES",
        "PRODUCT_TYPE",
        "EU_ID",
        "AGE DAYS",
        "FREEZE_DOWN",
        "CASE_SIZE",
        "BAG_SIZE",
        "ECOLI_TEST",
        "PIECES_BOX",
        "BAGS_BOX",
        "PFF_GTIN",
        "GTIN_12",
        "GTIN_14",
        "NOTES"
    ],
    "product": [
        "CODE_UID",
        "CODE_CRL",
        "STATUS ",
        "CODE_PFF",
        "PROGRAMS",
        "CODE_PFFshort",
        "CODE_CPM",
        "CODE_MR",
        "CODE_CFS",
        "CODE_BMP",
        "CODE_RMNM",
        "CODE_SKFP",
        "CODE_MCF",
        "CODE_NF",
        "DISCRIPTION",
        "CUT_TYPE",
        "SPECIES",
        "PRODUCT_TYPE",
        "EU_ID",
        "AGE DAYS",
        "FREEZE_DOWN",
        "CASE_SIZE",
        "BAG_SIZE",
        "ECOLI_TEST",
        "PIECES_BOX",
        "BAGS_BOX",
        "PFF_GTIN",
        "GTIN_12",
        "GTIN_14",
        "NOTES"
    ],
    "slaughter_rep": [
        "Animal PK",
        "Animal ID",
        "Slaughter Date",
        "Owner",
        "Shipper",
        "Live Weight",
        "Hot Weight",
        "Cold Weight",
        "Age",
        "Receiving Order ID",
        "Condemn",
        "Lot Number",
        "Species",
        "Sex",
        "Manifest ID",
        "Grading",
        "CSF Date"
    ],
    "harvest_report": [
        "Harvest Date",
        "Plant",
        "YEAR",
        "Period",
        "Quarter",
        "Location",
        "producer ID",
        "Producer/Owner",
        "Count",
        "M-UTM",
        "M-OTM",
        "F-UTM",
        "F-OTM",
        "F-COW",
        "M_A1",
        "M_A2",
        "M_A3",
        "M_A4",
        "M_B1",
        "M_B2",
        "M_B3",
        "M_D1",
        "M_D2",
        "M_D3",
        "F_A1",
        "F_A2",
        "F_A3",
        "F_A4",
        "F_B1",
        "F_B2",
        "F_B3",
        "F_D1",
        "F_D2",
        "F_D3",
        "PriorYRS B&H",
        "Prior YRS Mature",
        "Total Live(Lbs)",
        "PLANT AvgLive (Lbs)",
        "Live Helper",
        "LiveBullLbsHelper",
        "LiveHeifersLbsHelper",
        "LiveCowLbsHelper",
        "Total HHW (LBS)",
        "AvgHHW (Lbs)",
        "HHW Helper",
        "HHWBullLbsHelper",
        "HHWHeifersLbsHelper",
        "HHWCowLbsHelper",
        "Yield to Plant(%)",
        "Shrink Helper",
        "Avg$/lb",
        "$/lb Helper",
        "Avg$/hd",
        "$/hd Helper",
        "Week",
        "pre2024 Prod/Owner"
    ]
}

cutout_maps = {
    "headers": [
        "DATE",
        "LOT_NUMBER",
        "HD_AMOUNT",
        "TYPE",
        "LW_IN_KG",
        "LW_AVG_KG",
        "LW_AVG_LBS",
        "HHW_IN_KG",
        "HHW_AVG_KG",
        "HHW_AVG_LBS",
        "YIELD_DRESS",
        "CW_IN_KG",
        "CW_SHRINK",
        "CW_AVG_KG",
        "CW_AVG_LBS",
        "LIVE__DOLLER_PER_KG",
        "YEILD_CUT",
        "HHW_DOLLER_PER_KG",
        "HHW_AVG_KG",
        "HHW_AVG_LBS",
        "YEILD_MEAT",
        "BULLS_AMOUNT",
        "HEIFERS_AMOUNT",
        "COWS_AMOUNT",
        "MATURE",
        "HHW/HD_DOLLER_KG",
        "COST_HHW",
        "COST_PLANT/HD",
        "COST_PLANT",
        "COST_FOB",
        "COST_SGA/LB",
        "COST_SGA",
        "COST_KILL",
        "SELL_PRIMAL",
        "SELL_OFFAL",
        "SELL_PROFIT",
        "SELL_PRIMAL_HD",
        "SELL_OFFAL_HD",
        "MARGIN",
        "SELL_HD",
        "COST_HD",
        "PROFIT_HD",
        "EU_FX",
        "PRIMAL_KGS",
        "PRIMAL_AVG_DOLLER_KG",
        "KGS_HD_OFFAL",
        "YEILD_OFFALS",
        "OFFAL_KGS",
        "OFFAL_AVG_DOLLER_KG",
        "CODE_CRL",
        "SELL_KG",
        "KGS_TOTAL",
        "KGS_HD",
        "VALUE_TOTAL",
        "WT_PERCENT_CUTS",
        "VALUE_PERCENT",
        "COGS_KG",
        "COGS",
    ],
    "descriptions": [
        "Date",
        "Lot Number",
        "# of head",
        "Grade",
        "Live Weight in Kg",
        "kg",
        "lbs",
        "HHW Weight in Kg",
        "kg",
        "lbs",
        "Dressing yield",
        "Cold Weight in Kg",
        "Shrink",
        "TBD",
        "TBD",
        "Live price in KG",
        "Cut yield",
        "HHW price in KG",
        "kg",
        "lbs",
        "Meat Yield",
        "TBD",
        "NEW",
        "NEW",
        "NEW",
        "TBD",
        "COST of HHW Bison",
        "PLANT COST per head",
        "PLANT COST",
        "COST FOB Lacombe",
        "Selling, General, Admin. COST",
        "TBD",
        "Total COST for kill",
        "Sales price Revenue",
        "By-products Revenue",
        "NET PROFIT FOR KILL",
        "Primal per head",
        "Offal per head",
        "MARGIN",
        "Sales price Revenue",
        "Total cost per hd",
        "NET PROFIT per hd",
        "EU Exchange rate",
        "Total KG",
        "TBD",
        "per head total KG by-products (offals)",
        "per head total KG by-products (offals)",
        "Total KG",
        "TBD",
        "Code",
        "Sales Price #1 per kg",
        "Total kg",
        "Average kg per head",
        "TBD",
        "% weight of cuts",
        "% Value from av. kg sales price",
        "Product Inventory cost value/kg",
        "Product Inventory cost",
    ]
}

temp_dir = "./temp/1acutout"
listUsPlant = ["LNTZ", "BMP"]
listCanadaPlant = ["CPM", "PFF", "BVY"]
listExchangeStr = ["EXCHAN", "US @"]
temp_sales_dir = "./temp/sales"
header_cutoutmap = ["date", "lot_number", "hd_amount", "type_grade", "lw_in_kg", "lw_avg_kg", "lw_avg_lbs", "hhw_in_kg", "total_hhw_lbs", "hhw_avg_kg", "hhw_avg_lbs", "yield_dress", "cw_in_kg", "cw_shrink", "cw_avg_kg", "cw_avg_lbs", "live_dollar_per_kg", "yield_cut", "hhw_dollar_per_kg", "hhw_avg_kg_meat", "hhw_avg_lbs_meat", "yield_meat", "bulls_amount", "heifers_amount", "cows_amount", "doa_inpen", "hhw_dollar_per_lb", "cost_hhw", "cost_plant_hd", "cost_plant", "cost_fob", "cost_sga_lb",
                    "cost_sga", "cost_kill", "sell_primal", "sell_offal", "sell_profit", "sell_primal_hd", "sell_offal_hd", "margin", "sell_hd", "cost_hd", "profit_hd", "eu_fx", "primal_kgs", "primal_avg_dollar_kg", "kgs_hd_offal", "yield_offals", "offal_kgs", "offal_avg_dollar_kg", "code_crl", "sell_kg", "price_lb_usd", "kgs_total", "kgs_hd", "value_total", "wt_percent_cuts", "value_percent", "cogs_kg", "cogs", "fat_percent", "net_truck", "net_truck_shrink", "price_back_to_farm", "us_canada", "plant_name"]
