# Generated by Django 5.0 on 2024-11-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutoutmap',
            name='fat_percent',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
