# Generated by Django 5.0 on 2024-11-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_cutoutmap_fat_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoutmap',
            name='fat_percent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
