# Generated by Django 5.0 on 2024-11-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_alter_cutoutmap_fat_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cutoutmap',
            old_name='mature',
            new_name='doa_inpen',
        ),
    ]
